services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php-fpm/Dockerfile
    container_name: task-manager-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-task_manager}
      DB_USERNAME: ${DB_USERNAME:-task_manager}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/node/Dockerfile
    container_name: task-manager-frontend
    working_dir: /app
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-http://localhost:8080/api}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./docker/nginx
    container_name: task-manager-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootsecret}
      MYSQL_DATABASE: ${DB_DATABASE:-task_manager}
      MYSQL_USER: ${DB_USERNAME:-task_manager}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  frontend_node_modules:
